name: CI
on:
    pull_request:

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup pnpm
              uses: pnpm/action-setup@v4

            - name: Setup Node.js and pnpm cache
              uses: actions/setup-node@v3
              with:
                  node-version: "22"
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Run checks
              run: pnpm turbo check
